repositories implemented
nissemand243/Dwarfs_and_Giants pull request #76
Opened 2021-12-02 12:55 UTC by jeroleski

storage implmentations of User (ish), Rating, Tag, Comment (not material) -Repositories using IRepositories. And renaming of all DTO fields.

2021-12-02 17:46 UTC, ThomasITU requested changes
IAPIController.cs int parametre => camelCase

Comment.cs bør ikke kunne indholde null text - Deniz gav en forklaring på disc til at fixe warnings, linker det i vores resources
CommentId => Id

Material.cs - samme pointe til de fleste nullable properties ud over comments, ratings og muligvis tags
MaterialId => Id

Rating.cs
RatingId => Id

Tag.cs samme point omkring nullable som ovenfor
TagId => Id

MaterialDTO.cs
FileType til enum, DataAnnotation til [Url]FilePath

Ellers ser det godt ud 👍 

Udkommenteret kode i DatabaseContext.cs bør fjernes

Kan ikke sige så meget om funktionaliteten i Repositories, det fungere sikkert, men ingen der er ikke nogen tests  .
Navngivning i repositories bør være CRUD i dette lag og ikke http

2021-12-03 12:49 UTC, Rasmus-Balthazar commented on Infrastructure/Tag.cs
> +    public string? TagName { get; set; }
[Required]?

2021-12-04 13:14 UTC, Rasmus-Balthazar approved these changes
Der er nogle warnings med properties, det fikser vi i en anden branch

2021-12-05 16:26 UTC, jeroleski commented
> IAPIController.cs int parametre => came

2021-12-05 16:26 UTC, closed without merging